### ISSUE TITLE
Error when trying to open generated solution in Visual Studio 2015: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by drhaynes** [modesttree/Projeny#26]
After following the tutorial and setting up Unity to use the `PrjOpenInVisualStudio.bat` file, with arguments `"$(File)" "$(Line)"` as per below:

![projeny1](https://cloud.githubusercontent.com/assets/117291/15602571/ebb4c96a-23ed-11e6-91da-a7bd5bd1e870.png)

The error appears in the command prompt window when opening the solution by double-clicking an exception in the Unity Console window:

```
Determined Project = AllMovers, Platform = Windows
'NoneType' object is not subscriptable
Operation completed with errors.  Took 0.1 seconds.
Error occurred!  Unable to open visual studio.
Press any key to continue . . .
```

![image](https://cloud.githubusercontent.com/assets/117291/15602595/1c7100dc-23ee-11e6-936c-bee9eea96f34.png)

Looking at [OpenInVisualStudio.py l.49](https://github.com/modesttree/Projeny/blob/009a20a240467bf068ec37549578c6df5ccbdafb/Source/prj/main/OpenInVisualStudio.py#L49)
it appears that the issue is happening in the call to `self._vsSolutionHelper.openFile(self._args.filePath, lineNo, solutionPath)`

Perhaps the `_vsSolutionHelper` is `None` at this point, which suggests a misconfigured Projeny.yaml, however, the correct path to devenv.exe has been specified in Projeny.yaml as per below:

```
ProjectAliases:
    am: AllMovers
    cm: CubeMover
    sm: SphereMover

PathVars:
    UnityProjectsDir: '[ConfigDir]/UnityProjects'
    SharedUnityPackagesDir: '[ConfigDir]/UnityPackages'
    LogPath: '[ConfigDir]/PrjLog.txt'
    VisualStudioIdePath: 'C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/devenv.exe'
```

N.B The project opens fine when using the 'Open Solution' button in the Projeny Package Manager.

Any ideas? Thanks.
